import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SettingsProvider from "@/src/components/SettingsProvider";
import "./globals.css";
import UserMenu from "@/src/components/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SettingsProvider>
          <header className="border-b border-[var(--border)] bg-[var(--background)]">
            <div className="flex w-full items-start px-3 py-3 sm:px-6">
              <UserMenu />
            </div>
          </header>
          {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
